
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
  
  wordpress:
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html

  # mariadb:
  #   build: ./requirements/mariadb 
  #   networks:
  #     - inception
  #   volumes:
  #     - db_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  wp_data:
#   db_data: